version: '3'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: 'kafka'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  mongodb:
    image: mongo:5
    container_name: mongodb
    ports:
      - 27017:27017
  backend1:
    image: node:18
    container_name: backend1
    # to keep the container running
    command: "sleep infinity"
    links:
      - kafka
    volumes:
      # # use a host directory, to save work
      - ./:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 3000:3000
  backend2:
    image: node:18
    container_name: backend2
    command: "sleep infinity"
    links:
      - kafka
      - mongodb
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 4000:4000
